export enum MealRoutineState {
  ACTIVE_MEAL_ROUTINE_NULL = "ACTIVE_MEAL_ROUTINE_NULL",
  SELECTING_DATE_RANGE = "SELECTING_DATE_RANGE",
  SELECTING_MEALS = "SELECTING_MEALS",
  SHOPPING = "SHOPPING",
  CONFIRM_CREATION = "CONFIRM_CREATION",
  VIEWING = "VIEWING",
  COMPLETE = "COMPLETE",
}
